import globals from 'globals';
import pluginJs from '@eslint/js';

export default
[
  
  {
    languageOptions: {
      globals: globals.node
    }
  },
  
	pluginJs.configs.recommended,
  
  {
    rules: {

      /* ************* eslint ************* */

      'comma-dangle': [ 1, 'never' ],
      'for-direction': 1,
      'getter-return': [ 1, { allowImplicit: true }],
      'no-await-in-loop': 0,
      'no-compare-neg-zero': 1,
      'no-cond-assign': [ 1, 'always' ],
      'no-console': 'off',
      'no-constant-condition': 'off',
      'no-control-regex': 1,
      'no-debugger': 1,
      'no-dupe-args': 1,
      'no-dupe-keys': 1,
      'no-duplicate-case': 1,
      'no-empty': 1,
      'no-empty-character-class': 1,
      'no-ex-assign': 1,
      'no-extra-boolean-cast': 1,
      'no-extra-parens': [ 1, 'all', {
        conditionalAssign: false,
        enforceForArrowConditionals: false,
        ignoreJSX: 'all',
        nestedBinaryExpressions: false,
        returnAssign: false
      }],
      'no-extra-semi': 1,
      'no-func-assign': 1,
      'no-inner-declarations': [ 1, 'both' ],
      'no-invalid-regexp': 1,
      'no-irregular-whitespace': 1,
      'no-obj-calls': 1,
      'no-regex-spaces': 1,
      'no-sparse-arrays': 1,
      'no-unexpected-multiline': 1,
      'no-template-curly-in-string': 1,
      'no-unreachable': 1,
      'no-unsafe-finally': 1,
      'no-unsafe-negation': 1,
      'use-isnan': 1,
      'valid-jsdoc': 0,
      'valid-typeof': 1,
      'accessor-pairs': [ 1, { getWithoutSet: false, setWithoutGet: true }],
      'array-callback-return': [ 1, { allowImplicit: true }],
      'block-scoped-var': 1,
      complexity: 0,
      'consistent-return': 0,
      curly: [ 1, 'all' ],
      'default-case': 1,
      'dot-notation': [ 1, { allowKeywords: true }],
      eqeqeq: 1,
      'no-alert': 1,
      'no-caller': 1,
      'no-case-declarations': 1,
      'no-div-regex': 1,
      'no-empty-function': [ 1, { allow: [ 'methods' ] }],
      'no-eq-null': 1,
      'no-eval': 1,
      'no-extend-native': 1,
      'no-extra-bind': 1,
      'no-extra-label': 1,
      'no-fallthrough': 1,
      'no-floating-decimal': 1,
      'no-global-assign': 1,
      'no-implicit-coercion': 1,
      'no-implicit-globals': 1,
      'no-implied-eval': 1,
      'no-invalid-this': 0,
      'no-iterator': 1,
      'no-labels': 1,
      'no-lone-blocks': 1,
      'no-loop-func': 1,
      'no-magic-numbers': 0,
      'no-multi-spaces': 1,
      'no-multi-str': 1,
      'no-new': 1,
      'no-new-func': 1,
      'no-new-wrappers': 1,
      'no-octal': 1,
      'no-octal-escape': 1,
      'no-param-reassign': 0,
      'no-proto': 1,
      'no-redeclare': 1,
      'no-return-assign': [ 1, 'always' ],
      'no-script-url': 1,
      'no-self-assign': 1,
      'no-self-compare': 1,
      'no-sequences': 1,
      'no-throw-literal': 1,
      'no-unmodified-loop-condition': 1,
      'no-unused-expressions': 1,
      'no-unused-labels': 1,
      'no-useless-call': 1,
      'no-useless-concat': 1,
      'no-useless-escape': 1,
      'no-useless-return': 1,
      'no-void': 1,
      'no-warning-comments': 1,
      'no-with': 1,
      radix: 1,
      'vars-on-top': 1,
      'wrap-iife': [ 1, 'inside' ],
      yoda: [ 1, 'never' ],
      strict: [ 1, 'global' ],
      'init-declarations': 0,
      'no-catch-shadow': 1,
      'no-delete-var': 1,
      'no-label-var': 1,
      'no-restricted-globals': 1,
      'no-shadow': [ 1 ],
      'no-shadow-restricted-names': 1,
      'no-undef': 1,
      'no-undef-init': 1,
      'no-undefined': 0,
      'no-unused-vars': [ 1, { vars: 'all', args: 'after-used' }],
      'no-use-before-define': 'error',
      'handle-callback-err': [ 1, 'err' ],
      'no-buffer-constructor': 1,
      'no-mixed-requires': [ 1, true ],
      'no-new-require': 1,
      'no-path-concat': 1,
      'no-process-env': 1,
      'no-process-exit': 1,
      'no-restricted-modules': 0,
      'no-sync': 'off',
      'array-bracket-newline': 0,
      'array-bracket-spacing': [ 1, 'always', {
        singleValue: true,
        objectsInArrays: false,
        arraysInArrays: false
      }],
      'array-element-newline': 0,
      'block-spacing': [ 1, 'always' ],
      'brace-style': [ 1, 'stroustrup', { allowSingleLine: false }],
      'comma-spacing': [ 1, { before: false, after: true }],
      'comma-style': [ 1, 'last' ],
      'computed-property-spacing': [ 1, 'never' ],
      'consistent-this': [ 1, 'that' ],
      'eol-last': 1,
      'func-names': 0,
      'func-call-spacing': [ 1, 'never' ],
      'func-name-matching': 0,
      'func-style': [ 1, 'expression' ],
      'function-paren-newline': [ 1, 'consistent' ],
      'id-blacklist': 0,
      'id-length': 'off',
      'id-match': 0,
      'implicit-arrow-linebreak': 0,
      'jsx-quotes': [ 1, 'prefer-single' ],
      'key-spacing': [ 1, { beforeColon: false, afterColon: true, mode: 'strict' }],
      'keyword-spacing': [ 1, {
        before: true,
        after: false,
        overrides: {
          else: { after: true },
          import: { after: true },
          export: { after: true },
          from: { after: true },
          return: { after: true },
          case: { after: true },
          try: { after: true },
          const: { after: true },
          throw: { after: true }
        }
      }],
      'line-comment-position': [ 1, { position: 'above' }],
      'lines-around-comment': [ 1, {
        beforeBlockComment: false,
        afterBlockComment: false,
        beforeLineComment: true,
        afterLineComment: false,
        allowBlockStart: true,
        allowBlockEnd: true,
        allowObjectStart: true,
        allowObjectEnd: true,
        allowArrayStart: true,
        allowArrayEnd: true
      }],
      'lines-between-class-members': [ 1, 'always', { exceptAfterSingleLine: true }],
      'max-depth': 0,
      'max-len': 0,
      'max-nested-callbacks': 0,
      'max-params': 0,
      'max-statements': 0,
      'max-statements-per-line': [ 1, { max: 1 }],
      'multiline-comment-style': [ 1, 'separate-lines' ],
      'multiline-ternary': [ 1, 'always-multiline' ],
      'new-parens': 1,
      'newline-per-chained-call': [ 1, { ignoreChainWithDepth: 4 }],
      'no-array-constructor': 1,
      'no-bitwise': 1,
      'no-continue': 0,
      'no-inline-comments': 1,
      'no-lonely-if': 1,
      'no-mixed-spaces-and-tabs': [ 1 ],
      'no-multiple-empty-lines': [ 1, { max: 1 }],
      'no-negated-condition': 0,
      'no-nested-ternary': 1,
      'no-new-object': 1,
      'no-plusplus': [ 1, { allowForLoopAfterthoughts: true }],
      'no-restricted-syntax': 0,
      'no-ternary': 0,
      'no-trailing-spaces': [ 1, {
        ignoreComments: false,
        skipBlankLines: true
      }],
      'no-unneeded-ternary': 1,
      'no-whitespace-before-property': 1,
      'object-curly-newline': [ 1, {
        ObjectExpression: { consistent: true },
        ObjectPattern: { consistent: true }
      }],
      'object-curly-spacing': [ 1, 'always' ],
      'object-property-newline': [ 1, { allowAllPropertiesOnSameLine: true }],
      'one-var': 0,
      'one-var-declaration-per-line': [ 1, 'always' ],
      'operator-assignment': [ 1, 'always' ],
      'operator-linebreak': [ 1, 'after' ],
      'quote-props': [ 1, 'as-needed' ],
      quotes: [ 1, 'single', { avoidEscape: false, allowTemplateLiterals: true }],
      'require-jsdoc': 0,
      semi: [ 1, 'always' ],
      'semi-spacing': [ 1, { before: false, after: true }],
      'semi-style': [ 1, 'last' ],
      'sort-keys': [ 0 ],
      'sort-vars': [ 1, { ignoreCase: true }],
      'space-before-blocks': [ 1, 'always' ],
      'space-before-function-paren': [ 1, 'never' ],
      'space-in-parens': [ 1, 'never' ],
      'space-infix-ops': [ 1, { int32Hint: false }],
      'space-unary-ops': [ 1, { words: true, nonwords: false }],
      'spaced-comment': [ 1, 'always' ],
      'switch-colon-spacing': [ 1, { after: true, before: false }],
      'wrap-regex': 0,
      'arrow-body-style': 'off',
      'arrow-parens': [ 1, 'always' ],
      'arrow-spacing': [ 1, { before: true, after: true }],
      'constructor-super': 1,
      'generator-star-spacing': [ 1, { before: true, after: true }],
      'no-class-assign': 1,
      'no-confusing-arrow': 1,
      'no-const-assign': 1,
      'no-dupe-class-members': 'off',
      'no-duplicate-imports': 1,
      'no-new-symbol': 1,
      'no-restricted-imports': 0,
      'no-this-before-super': 1,
      'no-useless-computed-key': 1,
      'no-var': 1,
      'prefer-arrow-callback': [ 1, { allowNamedFunctions: false, allowUnboundThis: true }],
      'prefer-const': [ 1, { destructuring: 'any', ignoreReadBeforeAssign: true }],
      'prefer-numeric-literals': 1,
      'prefer-reflect': 'off',
      'prefer-rest-params': 1,
      'prefer-spread': 1,
      'prefer-template': 1,
      'require-yield': 1,
      'symbol-description': 1,
      'template-curly-spacing': [ 1, 'never' ],
      'yield-star-spacing': [ 1, { before: true, after: true }]
    }
  }
];

